ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
    get '/rental_requests', to: 'cat_rental_requests#index'
    # resources :rental_requests, only: [:index]
  end
  
  get '/rental_requests/new', to: 'cat_rental_requests#new'
  post '/rental_requests', to: 'cat_rental_requests#create'
  # resources :rental_requests, only: [:new, :create]
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'

class Cat < ApplicationRecord
  
  include ActionView::Helpers::DateHelper
  
  CAT_COLORS = %w(black brown white orange gray)
  
  validates :birth_date, :name, :color, :sex, presence: true
  validates :color, inclusion: { in: CAT_COLORS }
  validates :sex, inclusion: { in: %w(M F) }
  
  has_many :rentals,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy
  
  def self.colors
    CAT_COLORS
  end
  
  def age
    time_ago_in_words(birth_date)
  end
  
  def birth_date_s
    birth_date.to_s
  end
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validates :start_date, :end_date, :status, presence: true
  validate :does_not_overlap_approved_request
  
  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat
  
  def overlapping_requests
    CatRentalRequest.where(start_date: self.start_date..self.end_date)
    .where.not(id: self.id)
    .where(cat_id: self.cat_id)
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status:'APPROVED')
  end

  private
  
  def does_not_overlap_approved_request
    overlapping_approved_requests.exists?
  end
  
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  
  def index
    @requests = CatRentalRequest.all
    render :index
  end
  
  # def show
  #   @request = CatRentalRequest.find_by(id: params[:id])
  #   render :show
  # end
  
  def new
    @cats = Cat.all
    render :new
  end
  
  def create
    @request = CatRentalRequest.new(cat_rental_params)
    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      render json: @request.errors.full_messages, status: 422
    end
  end
  
  def cat_rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find_by(id: params[:id])
    @requests = @cat.rentals.order(:start_date)
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end
  
  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end
  
  private
  
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    
  end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cat_rental_requests/new.html.erb
<h1>Create a rental request</h1>

<form action="<%= rental_requests_url(@request) %>" method="post">
  
  <label for="cat">Cat</label>
  <select id="cat" name="cat_rental_request[cat_id]">
    <% @cats.each do |cat| %>
    <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  
  <label for="start_date">Start Date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]">
  <br>
  
  <label for="end_date">End Date</label>
  <input id="end_date" type="date" name="cat_rental_request[end_date]">
  <br>
  
  <input type="submit" value="Create Rental Request">
</form>

ninety_nine_cats/app/views/cats/_form.html.erb
<% 
  if action == :edit 
    action_url = cat_url(cat)
    button_text = "Update Cat"
  else
    action_url = cats_url
    button_text = "Create Cat"
  end
%>

<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  <br>
  
  <label>Sex</label>
  
  <label for="M">M</label>
  <input id="M" type="radio" name="cat[sex]" value = "M"<%= cat.sex == "M" ? "checked" : "" %> >
  
  <label for="F">F</label>
  <input id="F" type="radio" name="cat[sex]" value = "F"<%= cat.sex == "F" ? "checked" : "" %> >
  <br>
  
  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected" %> >-- select a color --</option>
    
    <% Cat.colors.each do |color| %>
      <option value="<%= color %>"
        <%= cat.color == color ? "selected" : "" %> ><%= color %></option>
    <% end %>
    
  </select>
  <br>
  
  <label for="birth_date">Birth Date</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date_s %>">
  <br>
  
  <label for="description">Description</label>
  <textarea id="description" name="cat[description]"><%= cat.description %></textarea>
  <br>
  
  <input type="submit" value="<%= button_text %>">
  
</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Edit cat</h1>
<%= render 'form', cat: @cat, action: :edit %>

ninety_nine_cats/app/views/cats/index.html.erb
<h1>All the cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li> <%= cat.name %> </li>
    <a href= " <%= cat_url(cat) %>">Show Cat</a>  
  <% end %> 
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h1>Create a cat</h1>
<%= render 'form', cat: @cat, action: :new %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    
    <tr>
      <td>Age</td>
      <td> <%= @cat.age %> </td>
    </tr>
    
    <tr>
      <td>Birth_Date</td>
      <td> <%= @cat.birth_date %> </td>
    </tr>
    
    <tr>
      <td>Color</td>
      <td> <%= @cat.color %> </td>
    </tr>
    
    <tr>
      <td>Sex</td>
      <td> <%= @cat.sex %> </td>
    </tr>
</table>

<h1>Rental Requests</h1>
<% if @requests.empty? %>
  <p><%= @cat.name %> has no rental requests</p>
  
<% else %>
  <table>
    <tr>
      <!-- <th>User</th> -->
      <th>Start_Date</th>
      <th>End_Date</th>
      <th>Status</th>
    </tr>
    <% @requests.each do |request| %>
      <tr>
        <td> <%= request.start_date %> </td>
        <td> <%= request.end_date %> </td>
        <td> <%= request.status %> </td>
      </tr>
    <% end %>
    
  </table>
  
<% end %>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>